apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: test-post
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - |
            payload={
              "channel": "#somechannel",
              "username": "hello",
              "text": "App Sync succeeded",
              "icon_emoji": ":ghost:"
            }
          - "https://webhook-test.com/3eb648b21415c35a13f142c58048a874"
      restartPolicy: Never
  backoffLimit: 2
