apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: test-post
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Accept: application/vnd.github.v3+json"
          - "-H"
          - "Authorization: token test_value"
          - "-d"
          - |
            {
              "name": "test",
              "namespace": "argocd",
              "slackchannel": "testing"
            }
          - "https://webhook-test.com/3eb648b21415c35a13f142c58048a874"
      restartPolicy: Never
  backoffLimit: 2
